### ISSUE TITLE
缺少json验证

### ISSUE THREAD

**Issue by ahxukai** [devefx/validator#1]
楼主发验证框架是绑定在controller入口的，针对的是前台以form表单提交的数据验证，现在都用json提交数据了，json到后台只是一串字符串，需要转换为对应的类或者map或者jsonobjecct，不知道楼主有没有想过怎么验证json里面的数据

**Comment by devefx** [comment]
后台并不知道数据的提交方式，都能从**HttpServletRequest**中通过**getParameter**获取请求参数，
至于前端对json数据验证并没有考虑过这种做法。如果你想要扩展，可以对**validator.js**的Request就行扩展，将验证的数据来源换成**json**

`function Request(data) {

    this.data = data;
    this.getParameter = function (name) {
        try {
            return this.data[name];
        } catch (e) {
            return null;
        }
    };
}`
